base_images:
  base:
    name: "4.8"
    namespace: ocp
    tag: base
  cli:
    name: "4.8"
    namespace: ocp
    tag: cli
  ocp_builder_rhel-8-golang-1.16-openshift-4.8:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.16-openshift-4.8
  os:
    name: centos
    namespace: origin
    tag: "8"
  ubi_minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
binary_build_commands: make all
build_root:
  project_image:
    dockerfile_literal: |
      FROM registry.fedoraproject.org/fedora:33
      USER root
      RUN dnf install -y ShellCheck yamllint asciidoctor && \
          dnf install -y make go diffutils openssl && \
          dnf clean all && rm -rf /var/cache/dnf/*
      RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
          chmod 700 get_helm.sh && \
          ./get_helm.sh
      ENV GOPATH=/go GOCACHE=/go/src/.cache GO111MODULE=on
      RUN mkdir -p $GOCACHE /.cache $GOPATH/src/github.com/backube/testbin
      RUN chmod -R 777 /go /.cache
      RUN curl -sSLo envtest-bins.tar.gz "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.19.2-$(go env GOOS)-$(go env GOARCH).tar.gz"
      RUN tar -C $GOPATH/src/github.com/backube/testbin --strip-components=1 -zvxf envtest-bins.tar.gz
      WORKDIR $GOPATH/src/github.com/backube/scribe
images:
- dockerfile_literal: |
    FROM src
    COPY oc /usr/bin/oc
    RUN ln -s /usr/bin/oc /usr/bin/kubectl
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: src-oc
- context_dir: .
  from: ubi_minimal
  inputs:
    ocp_builder_rhel-8-golang-1.16-openshift-4.8:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.8
  to: scribe
- context_dir: mover-rclone
  from: os
  to: scribe-mover-rclone
- context_dir: mover-restic
  from: ubi_minimal
  to: scribe-mover-restic
- context_dir: mover-rsync
  from: os
  to: scribe-mover-rsync
promotion:
  additional_images:
    scribe: scribe
    scribe-mover-rclone: scribe-mover-rclone
    scribe-mover-restic: scribe-mover-restic
    scribe-mover-rsync: scribe-mover-rsync
  namespace: scribe
  tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.8"
resources:
  '*':
    limits:
      memory: 6Gi
    requests:
      cpu: 500m
      memory: 1Gi
tests:
- as: e2e-test
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      commands: |
        ./hack/run-minio.sh
        oc -n minio wait --for=condition=Available --timeout=300s deploy/minio
        make test-e2e
      from: src-oc
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
    workflow: ipi-aws-scribe-csi
zz_generated_metadata:
  branch: master
  org: backube
  repo: scribe
